#cloud-config
packages:
- pwgen
- pastebinit
- [libpython3.8, 3.8.10-0ubuntu1~20.04.2]
- snap:
  - certbot
  - [juju, --edge]
  - [lxd, --channel=5.15/stable]
- apt:
  - mg
package_update: true
package_upgrade: true
package_reboot_if_required: true
